### ISSUE TITLE
Pretty messages for known errors

### ISSUE THREAD

**Issue by dplummer** [crystalcommerce/cc-cli#5]
For know exceptions, lets print out the errors nicely, with information to the user on what they should to do fix it. Add a `--backtrace` flag to add the backtrace to the output for us when we need to troubleshoot something.

For example, this:

```
[dplummer@ccdev1:~]$ cc-cli catalog products --available-cols
GET https://api.crystalcommerce.com/v1/catalog/products?page=1 
/home/dplummer/.rvm/gems/ruby-2.1.1/gems/cc-cli-0.0.1/lib/cc/api/http/http_requestor.rb:31:in `request_for_json': There's a problem with the server. Server response not expected. (Cc::Api::Http::ServerProblemException)
    from /home/dplummer/.rvm/gems/ruby-2.1.1/gems/cc-cli-0.0.1/lib/cc/api/explorer.rb:143:in `perform'
    from /home/dplummer/.rvm/gems/ruby-2.1.1/gems/cc-cli-0.0.1/lib/cc/api/explorer.rb:93:in `catalog'
    from /home/dplummer/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /home/dplummer/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /home/dplummer/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /home/dplummer/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /home/dplummer/.rvm/gems/ruby-2.1.1/gems/cc-cli-0.0.1/bin/cc-cli:5:in `<top (required)>'
    from /home/dplummer/.rvm/gems/ruby-2.1.1/bin/cc-cli:23:in `load'
    from /home/dplummer/.rvm/gems/ruby-2.1.1/bin/cc-cli:23:in `<main>'
    from /home/dplummer/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
    from /home/dplummer/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```

Should be:

```
[dplummer@ccdev1:~]$ cc-cli catalog products --available-cols
GET https://api.crystalcommerce.com/v1/catalog/products?page=1 
There's a problem with the server. Server response not expected. Please contact api support.
```

Or something like that.

**Comment by dplummer** [comment]
If we could print out the message we got from the server, along with the http status code, that'd help too.
